#  Docker File is a declarative way of creating images and 
#  FROM is the first command in an Image
# command :- docker build -t[docker-hub-URL]/[username]/[imagename]:version
# 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  -- push token

FROM almalinux    